// <auto-generated />
using DockerCity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DockerCity.Data.Migrations
{
    [DbContext(typeof(DockerCityDbContext))]
    [Migration("20260922142318_HideProjectsFromRecent")]
    partial class HideProjectsFromRecent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("DockerCity.Data.Entities.AppSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("DockerCity.Data.Entities.ComposeProjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHiddenFromRecent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastOpenedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.ToTable("ComposeProjects");
                });

            modelBuilder.Entity("DockerCity.Data.Entities.ImageMappingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconFileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Pattern", "MatchMode")
                        .IsUnique();

                    b.ToTable("ImageMappings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            DisplayName = "PostgreSQL",
                            IconFileName = "postgres.png",
                            MatchMode = 0,
                            Pattern = "postgres",
                            Priority = 100
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            DisplayName = "MySQL",
                            IconFileName = "mysql.png",
                            MatchMode = 0,
                            Pattern = "mysql",
                            Priority = 100
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            DisplayName = "MariaDB",
                            IconFileName = "mariadb.png",
                            MatchMode = 0,
                            Pattern = "mariadb",
                            Priority = 100
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            DisplayName = "MongoDB",
                            IconFileName = "mongo.png",
                            MatchMode = 0,
                            Pattern = "mongo",
                            Priority = 100
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            DisplayName = "Redis",
                            IconFileName = "redis.png",
                            MatchMode = 0,
                            Pattern = "redis",
                            Priority = 100
                        },
                        new
                        {
                            Id = 6,
                            Category = 1,
                            DisplayName = "Qdrant",
                            IconFileName = "qdrant.png",
                            MatchMode = 0,
                            Pattern = "qdrant/qdrant",
                            Priority = 100
                        },
                        new
                        {
                            Id = 7,
                            Category = 2,
                            DisplayName = "RabbitMQ",
                            IconFileName = "rabbitmq.png",
                            MatchMode = 0,
                            Pattern = "rabbitmq",
                            Priority = 100
                        },
                        new
                        {
                            Id = 8,
                            Category = 2,
                            DisplayName = "NATS",
                            IconFileName = "nats.png",
                            MatchMode = 0,
                            Pattern = "nats",
                            Priority = 100
                        },
                        new
                        {
                            Id = 9,
                            Category = 3,
                            DisplayName = "MinIO",
                            IconFileName = "minio.png",
                            MatchMode = 0,
                            Pattern = "minio/minio",
                            Priority = 100
                        },
                        new
                        {
                            Id = 10,
                            Category = 3,
                            DisplayName = "FTP Server",
                            IconFileName = "ftp.png",
                            MatchMode = 0,
                            Pattern = "delfer/alpine-ftp-server",
                            Priority = 100
                        },
                        new
                        {
                            Id = 11,
                            Category = 4,
                            DisplayName = "Keycloak",
                            IconFileName = "keycloak.png",
                            MatchMode = 0,
                            Pattern = "keycloak/keycloak",
                            Priority = 100
                        },
                        new
                        {
                            Id = 12,
                            Category = 5,
                            DisplayName = "pgAdmin",
                            IconFileName = "pgadmin.png",
                            MatchMode = 0,
                            Pattern = "dpage/pgadmin4",
                            Priority = 100
                        },
                        new
                        {
                            Id = 13,
                            Category = 5,
                            DisplayName = "SonarQube",
                            IconFileName = "sonarqube.png",
                            MatchMode = 0,
                            Pattern = "sonarqube",
                            Priority = 100
                        },
                        new
                        {
                            Id = 14,
                            Category = 6,
                            DisplayName = "Nginx",
                            IconFileName = "nginx.png",
                            MatchMode = 0,
                            Pattern = "nginx",
                            Priority = 100
                        },
                        new
                        {
                            Id = 15,
                            Category = 6,
                            DisplayName = "Traefik",
                            IconFileName = "traefik.png",
                            MatchMode = 0,
                            Pattern = "traefik",
                            Priority = 100
                        },
                        new
                        {
                            Id = 16,
                            Category = 1,
                            DisplayName = "PostgreSQL",
                            IconFileName = "postgres.png",
                            MatchMode = 2,
                            Pattern = "postgres",
                            Priority = 10
                        },
                        new
                        {
                            Id = 17,
                            Category = 1,
                            DisplayName = "MySQL",
                            IconFileName = "mysql.png",
                            MatchMode = 2,
                            Pattern = "mysql",
                            Priority = 10
                        },
                        new
                        {
                            Id = 18,
                            Category = 1,
                            DisplayName = "Redis",
                            IconFileName = "redis.png",
                            MatchMode = 2,
                            Pattern = "redis",
                            Priority = 10
                        },
                        new
                        {
                            Id = 19,
                            Category = 1,
                            DisplayName = "Elasticsearch",
                            IconFileName = "elasticsearch.png",
                            MatchMode = 2,
                            Pattern = "elasticsearch",
                            Priority = 10
                        },
                        new
                        {
                            Id = 20,
                            Category = 2,
                            DisplayName = "Kafka",
                            IconFileName = "kafka.png",
                            MatchMode = 2,
                            Pattern = "kafka",
                            Priority = 10
                        },
                        new
                        {
                            Id = 21,
                            Category = 2,
                            DisplayName = "RabbitMQ",
                            IconFileName = "rabbitmq.png",
                            MatchMode = 2,
                            Pattern = "rabbitmq",
                            Priority = 10
                        },
                        new
                        {
                            Id = 22,
                            Category = 4,
                            DisplayName = "Keycloak",
                            IconFileName = "keycloak.png",
                            MatchMode = 2,
                            Pattern = "keycloak",
                            Priority = 10
                        },
                        new
                        {
                            Id = 23,
                            Category = 3,
                            DisplayName = "MinIO",
                            IconFileName = "minio.png",
                            MatchMode = 2,
                            Pattern = "minio",
                            Priority = 10
                        },
                        new
                        {
                            Id = 24,
                            Category = 6,
                            DisplayName = "Nginx",
                            IconFileName = "nginx.png",
                            MatchMode = 2,
                            Pattern = "nginx",
                            Priority = 10
                        });
                });

            modelBuilder.Entity("DockerCity.Data.Entities.ServiceLayoutEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComposeProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ComposeProjectId", "ServiceName")
                        .IsUnique();

                    b.ToTable("ServiceLayouts");
                });

            modelBuilder.Entity("DockerCity.Data.Entities.ServiceLayoutEntity", b =>
                {
                    b.HasOne("DockerCity.Data.Entities.ComposeProjectEntity", "ComposeProject")
                        .WithMany("Layouts")
                        .HasForeignKey("ComposeProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComposeProject");
                });

            modelBuilder.Entity("DockerCity.Data.Entities.ComposeProjectEntity", b =>
                {
                    b.Navigation("Layouts");
                });
#pragma warning restore 612, 618
        }
    }
}
