// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind";

/**
 * What the front end receives when a command fails. Tauri serialises the
 * `Err` side of a command's `Result`, so this type must be `Serialize`.
 */
export type AppError = { kind: ErrorKind, message: string, };
