// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpstreamDto } from "./UpstreamDto";

export type BranchStatsDto = { name: string, isRemoteOnly: boolean, lane: number | null, tipColumn: number, ahead: number, behind: number, merged: boolean, stale: boolean, lastActivity: number, commitCount: number, authors: Array<string>, upstream: UpstreamDto | null, };
