// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommitDto = { id: string, shortId: string, summary: string, authorName: string, authorEmail: string, 
/**
 * Committer time, seconds since the Unix epoch.
 */
time: number, parents: Array<string>, lane: number, isMerge: boolean, };
