// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParentDto } from "./ParentDto";
import type { PersonDto } from "./PersonDto";

export type CommitDetailsDto = { id: string, shortId: string, column: number, lane: string, summary: string, message: string, author: PersonDto, committer: PersonDto, parents: Array<ParentDto>, 
/**
 * Branches whose history contains this commit.
 */
branches: Array<string>, 
/**
 * Tags pointing exactly at this commit.
 */
tags: Array<string>, };
