// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchStatsDto } from "./BranchStatsDto";
import type { CommitDetailsDto } from "./CommitDetailsDto";
import type { MetroMapDto } from "./MetroMapDto";

/**
 * Everything the browser-only demo mode needs, in one file. Only built by
 * the `export_demo_map` test, hence `allow(dead_code)`.
 */
export type DemoBundle = { map: MetroMapDto, stats: Array<BranchStatsDto>, details: Array<CommitDetailsDto>, };
