// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HeadDto = { "kind": "branch", name: string, target: string, } | { "kind": "detached", target: string, } | { "kind": "unborn", name: string, };
