// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LabelKind } from "./LabelKind";

export type LaneDto = { id: number, label: string, labelKind: LabelKind, row: number, compactRow: number, color: number, refs: Array<string>, firstColumn: number, lastColumn: number, forkColumn: number | null, };
