// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitDto } from "./CommitDto";
import type { HeadDto } from "./HeadDto";
import type { LaneDto } from "./LaneDto";
import type { RefDto } from "./RefDto";
import type { TransitionDto } from "./TransitionDto";

export type MetroMapDto = { commits: Array<CommitDto>, lanes: Array<LaneDto>, transitions: Array<TransitionDto>, refs: Array<RefDto>, head: HeadDto, 
/**
 * Older history exists but was cut off by the limit.
 */
truncated: boolean, };
