// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParentDto = { id: string, shortId: string, 
/**
 * `null` when the parent lies beyond the loaded history window.
 */
column: number | null, };
