// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonDto = { name: string, email: string, time: number, 
/**
 * Minutes east of UTC, as recorded in the commit.
 */
offsetMinutes: number, };
