// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefKindDto } from "./RefKindDto";

export type RefDto = { name: string, kind: RefKindDto, column: number, };
