// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeadDto } from "./HeadDto";

export type RepoSummary = { name: string, path: string, head: HeadDto, };
