// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransitionKindDto } from "./TransitionKindDto";

export type TransitionDto = { kind: TransitionKindDto, fromLane: number, fromColumn: number, toLane: number, toColumn: number, };
