[package]
name = "mission_control"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.16"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
opt-level = "s"
lto = "thin"
